---
title: "Pregnancy Script: Data Model"
output: 
  rmdformats::robobook:
    css: styles.css
params:
  list_of_datamodel: NULL
  Description: NULL
  list_of_group: NULL
---


<br>

The Pregnancy Algorithm is composed of multiple steps. In each step, one or more datasets are required as input and one or more new datasets are produced as output. This page described the data models of such datasets.

<br><br><br>
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

```{r, include=FALSE}
# Init Step to make sure that the dependencies are loaded
htmltools::tagList(datatable(cars))
#htmltools::tagList(ggplotly(ggplot()))
```

```{r, results='asis'}

for(group in list_of_group){
   cat('  \n')
   cat("# ", group, " \n")
   cat('  \n')
   cat('___') 
   #cat('  \n')
   
   for (name_DM in list_of_datamodel[[group]]){
      DM <- read_excel(paste0(dirinput, "Data_Model.xlsx"), sheet = name_DM)
      cat('  \n')  
      cat("##", name_DM, "\n") 
      cat('  \n')  
      cat(as.character(Description[Description$A == name_DM, 2]), "\n")
      cat('\n') 
      
      print(htmltools::tagList(datatable(DM)))
      #tab = DM %>%
      #        kbl() %>%
      #        add_header_above()
       
      #cat(tab)
      
      cat('\n')
      cat('<br><br><br>') 
      cat('\n')
   }
   cat('<br><br><br><br><br>') 
   cat('\n')
}

```


